### ISSUE TITLE
"Automation" cannot select host in add sandbox

### ISSUE THREAD

**Issue by MatthewKahle** [alertflex/cnode#10]
Hi Alertflex,

Although I have a valid host configured for Suricata IDS, I cannot select a "host" nothing populates for this. I know this must be a bug.

URL where issue is at :xxxIPxxx/alertflex-mc/user/add-sandbox.xhtml

![image](https://user-images.githubusercontent.com/68342957/111107778-da742780-852d-11eb-8f7a-6570a91be177.png)

**Comment by olegzhr** [comment]
Hi Matt,

to fix this issue, you need to download the new management console war file ( https://github.com/alertflex/cnode/releases/download/v0.8-beta/alertflex-mc.war ) to Payara AS server

After that please follow the next procedure to create a playbook:

1) create playbook via web-form /Automation/playbooks/add 
2) go to  web-form /Automation/Playbooks/view and select created playbook name from the left menu of web-form
2)  to create the new job for playbook select Job type from the left menu, a new block should be added in the playbook diagram
4) click by mouse on this block  - an Edit Job web-form should be open
5) fill up needed parameters in the Edit Job web-form

Regards

**Comment by MatthewKahle** [comment]
Thanks for the clarification Olegzhr, I am now able to fill out the playbook. 

Thanks!
