### ISSUE TITLE
Cannot create a new host mapping

### ISSUE THREAD

**Issue by MatthewKahle** [alertflex/cnode#8]
Hi Alertflex team,

I decided to try and test your project, I like what I see so far, however one problem, I just finished installing the altprobe locally on the collector box. I tried mapping a "new host" for just IDS collection, however it will not allow me to create a sensor mapping without defining a host.. My problem is I get an error message and I assume this is because I didn't select an Agent. Now since this "host" is just for Suricata IDS alerts, why would I need to map it to Agent? Also there is no area for me to define the "Agent" perhaps this is a missing feature? 

Attached is when I try saving the new host mapping and as you can see there is no agent defined. 
![image](https://user-images.githubusercontent.com/68342957/109075376-076bb200-76c7-11eb-93bc-15d061182529.png)

**Comment by olegzhr** [comment]
Hi,

the problem with creating a host (if an agent is not defined) is SW bug, I will fix it, thank you.
Regarding to creating hosts and agents, maybe I didn't understand your question.
Anyway will try to describe this functionality.

You need to create a host and credential only for automation tasks. For example in the response to the alert you
want to execute a script on the host. In this case, you need to create a credential with the user/password and connect it with the host.
After that, you can indicate the host in the Script job of the playbook.

Concerning to area of creating an agent from the management console, it functions that implement API interface to Wazuh manager.
So you can from web UI to create Wazuh agent and see the parameters of agents, it simplifies the management of agents - no need to go to Unix console for creation agent.
If you have other questions, please ask them via discord server - https://discord.gg/wDSz7rDMWv
![agent](https://user-images.githubusercontent.com/14097456/109201804-eaa8aa80-77aa-11eb-9515-8ff6307fb18e.png)

**Comment by MatthewKahle** [comment]
Hey Olegzhr,

Ah I understand now, it has to be mapped under Wazuh agents. I guess my
real question is, do I need to have a defined Agent to create a host? Or is
that a bug you're fixing?
I'll be sure to jump into your Discord at some point real soon.

Best,
--
Matt

**Comment by olegzhr** [comment]
Hi Matt,

the field "Agent" should be an optional parameter in the web-form "Host". But at this moment it behaves as a mandatory parameter, so it is a bug that I am going to fix.

**Comment by MatthewKahle** [comment]
Looking forward to testing it once the bug it fixed.

**Comment by olegzhr** [comment]
new release v0.8-beta includes a fix for this issue (Cannot create a new host mapping)

**Comment by MatthewKahle** [comment]
I'll update my packages (maybe create a new VM) and I'll let you know know how the test of the release goes.

**Comment by MatthewKahle** [comment]
Hey olegzhr, 

Your release diffidently fixed this issue, thanks!
